# =====================================================================
# Engine metadata
# =====================================================================

engine.name=${project.name}
engine.version=${project.version}
engine.author=${project.organization.name}

# =====================================================================
# Openings book utilities
# =====================================================================

# ggp.book.export.input=
# ggp.book.export.min-count=
# ggp.book.export.output=

# ggp.book.query.roots=
# ggp.book.query.suite=

# ggp.book.train.bias=
# ggp.book.train.depth=
# ggp.book.train.engine=
# ggp.book.train.movetime=
# ggp.book.train.nodes=
# ggp.book.train.path=
# ggp.book.train.threads=

# =====================================================================
# Match against an engine
# =====================================================================

# ggp.match.command=
# ggp.match.control=
# ggp.match.debug=
# ggp.match.depth=
# ggp.match.increment=
# ggp.match.movetime=
# ggp.match.uci-option=

# =====================================================================
# UCI protocol service
# =====================================================================

# ggp.service.engine=

# =====================================================================
# Interactive UCI shell
# =====================================================================

# ggp.shell.command=
# ggp.shell.debug=

# =====================================================================
# Game suite utilities
# =====================================================================

# ggp.suite.random.depth=
# ggp.suite.random.endgame=
# ggp.suite.random.size=

# ggp.suite.show.file=

# =====================================================================
# Engine test utilities
# =====================================================================

# ggp.test.battle.command=
# ggp.test.battle.debug=
# ggp.test.battle.depth=
# ggp.test.battle.matches=
# ggp.test.battle.movetime=
# ggp.test.battle.rounds=
# ggp.test.battle.suite=
# ggp.test.battle.watch=

# ggp.test.bench.depth=
# ggp.test.bench.engine=
# ggp.test.bench.file=
# ggp.test.bench.movetime=

# ggp.test.divide.depth=
# ggp.test.divide.file=

# ggp.test.perft.depth=
# ggp.test.perft.file=
# ggp.test.perft.min-depth=
